# Generated by Django 5.2.1 on 2025-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='role',
            field=models.CharField(choices=[('organizer', 'Организатор'), ('volunteer', 'Волонтёр')], default='volunteer', max_length=20, verbose_name='Роль'),
        ),
    ]
